spring:
  datasource:
    url: jdbc:mysql://localhost:3307/main?serverTimezone=Asia/Jerusalem
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/