spring:
  datasource:
    url: jdbc:mysql://microservice-mysql:3306/main?serverTimezone=Asia/Jerusalem
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://microservice-registry:8761/eureka/